### PR TITLE
Add pyyaml and pandas to requirements file.

### PR DESCRIPTION
**Pull request by raquel-ucl**
I was going to add to `setup`:

```
install_requires=[
   'pandas',
   'pyyaml'
]
```

but the `setup` being used is from distutils which doesn't support `install_requires`. 
Also it's probably not a good idea to make everyone install these modules by default since it's planned that the imports for pandas and pyyaml are moved and not every project using DCPYPS will need to install them.

People can install this requirements as:

```pip install -r requirements.txt```

### CODE REVIEW

**Comment by raquel-ucl** [comment]
@remislp merge when you are ready, please.

**Comment by jenshnielsen** [comment]
Unless you have a good reason for selecting exactly those versions i strongly suggest removing v
the version specifications. This will cause a downgrade if you have a newer version installed

**Comment by jenshnielsen** [comment]
otherwise it's better to use >= than == if you need at lease some version due to requirements.

**Comment by raquel-ucl** [comment]
Done.

**Pull request merged**
